# syntax = docker/dockerfile:1

# Make sure RUBY_VERSION matches the Ruby version in .ruby-version and Gemfile
ARG RUBY_VERSION=3.4.2
FROM registry.docker.com/library/ruby:$RUBY_VERSION-slim-bookworm

RUN gem install foreman

# Rails app lives here
WORKDIR /rails

# Set production environment
ENV RAILS_ENV="production" \
    BUNDLE_DEPLOYMENT="1" \
    BUNDLE_PATH="/usr/local/bundle" \
    BUNDLE_WITHOUT="development"

# Install packages needed to build gems
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential git libvips pkg-config libpq-dev libsqlite3-dev libmariadb-dev imagemagick  chromium chromium-driver libyaml-dev

# Install application gems
COPY Gemfile Gemfile.lock ./
RUN bundle install -j20 && \
    rm -rf ~/.bundle/ "${BUNDLE_PATH}"/ruby/*/cache "${BUNDLE_PATH}"/ruby/*/bundler/gems/*/.git 

# Copy application code
COPY . .
RUN cp config/database.yml.sqlite3 config/database.yml
ENV RAILS_ENV=test
RUN ./bin/rails db:create db:migrate
