#!/usr/bin/env ruby

require "optparse"

options = {}
ARGV.options do |opt|
  opt.on("-d", "--daemon", "Run daemonized in the background") { |v| options[:daemon] = v }
  opt.on("-f", "--force", "Crawl all feeds regardless of the crawler's status") { |v| options[:force] = v }
  opt.on("-l", "--log=FILE", "Where to write log messages") { |v| options[:log_file] = v }
  opt.on("-p", "--pid=FILE", "Where to write the PID") { |v| options[:pid_file] = v }
  opt.on("-e", "--environment=NAME", "Specifies the environment to run this server under (test/development/production)") { |v| ENV['RAILS_ENV'] = v }
  opt.parse!
end

require File.expand_path('../../config/environment', __FILE__)
require "fastladder/crawler"

if options[:daemon]
  options[:log_file] ||= Rails.root.join('log', 'crawler.log')
  pidfile = options[:pid_file] || Rails.root.join('tmp', 'pids', 'crawler.pid')
  Process.daemon
  FileUtils.mkdir_p pidfile.dirname
  open(pidfile, 'w') { |f| f << Process.pid }
  File.umask(0)
end

Fastladder::Crawler.start(options)
begin
  File.delete(options[:pid_file]) if File.exists?(options[:pid_file])
rescue
end
